version: '2'
services:
  db:
    image: mariadb
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

  web70:
    build: "images/web70"
    volumes:
      - "./www:/var/www/html"
    depends_on:
      - db
    links:
      - db
    ports:
      - "8070:80"

  web56:
    build: "images/web56"
    volumes:
      - "./www:/var/www/html"
    depends_on:
      - db
    links:
      - db
    ports:
      - "8056:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - UPLOAD_LIMIT=300M
    depends_on:
      - db
